# Generated by Django 5.2.7 on 2025-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', '🟢 Active'), ('completed', '⚪️ Completed Successfully'), ('failed', '❌ Verification Failed'), ('terminated', '🔴 Terminated by Agent')], default='active', max_length=20),
        ),
    ]
