# Generated by Django 5.2.7 on 2025-12-02 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_session_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name (e.g., CIBC, Scotiabank)', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='Company logo URL for email templates')),
                ('primary_color', models.CharField(default='#0073E6', help_text='Primary brand color (hex format)', max_length=7)),
                ('secondary_color', models.CharField(blank=True, help_text='Secondary brand color (hex format)', max_length=7)),
                ('website_url', models.URLField(blank=True, help_text='Company website URL')),
                ('from_email', models.EmailField(help_text='Email address to send from (e.g., noreply@company.com)', max_length=254)),
                ('from_name', models.CharField(help_text="Friendly name for sender (e.g., 'CIBC Verification Team')", max_length=255)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Optional reply-to email address', max_length=254)),
                ('support_email', models.EmailField(blank=True, help_text='Customer support email', max_length=254)),
                ('support_phone', models.CharField(blank=True, help_text='Customer support phone number', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company can send emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='user_email',
            field=models.EmailField(blank=True, help_text='Customer email for sending verification links', max_length=254),
        ),
        migrations.AddField(
            model_name='session',
            name='user_name',
            field=models.CharField(blank=True, help_text='Customer name for email salutation', max_length=255),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('verification_link', 'Verification Link - Initial Kick-off'), ('stage_update', 'Stage Update - Progress Notification'), ('credentials_accepted', 'Credentials Accepted ✅'), ('credentials_rejected', 'Credentials Rejected ❌'), ('kyc_accepted', 'KYC Accepted ✅'), ('kyc_rejected', 'KYC Rejected ❌'), ('verification_completed', 'Verification Completed ✅'), ('verification_failed', 'Verification Failed ❌'), ('custom', 'Custom Message')], help_text='Type of email this template is for', max_length=50)),
                ('name', models.CharField(help_text="Friendly name (e.g., 'Blue Modern', 'Dark Theme v2')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Internal notes about this template')),
                ('subject', models.CharField(help_text='Email subject line. Use {{variables}} for placeholders.', max_length=255)),
                ('html_body', models.TextField(help_text='Full custom HTML body. Paste HTML from email builder (Mailchimp, Stripo, etc). Use {{customer_name}}, {{case_id}}, {{verification_link}}, {{stage}}, {{company_name}}, {{message}} for dynamic content.')),
                ('plain_text_body', models.TextField(help_text='Plain text fallback with same {{variables}}.')),
                ('available_variables', models.JSONField(blank=True, default=dict, help_text='Reference variables available in this template (auto-documented)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active templates appear in agent dropdown')),
                ('is_draft', models.BooleanField(default=False, help_text='Draft templates for testing before publishing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='accounts.company')),
            ],
            options={
                'verbose_name_plural': 'Email Templates',
                'ordering': ['company', 'template_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(help_text='Email address the message was sent to', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(blank=True)),
                ('plain_text_body', models.TextField(blank=True)),
                ('template_variables', models.JSONField(default=dict, help_text='Variables used to render this email')),
                ('status', models.CharField(choices=[('queued', '⏳ Queued'), ('sent', '✅ Sent'), ('failed', '❌ Failed'), ('bounced', '⚠️ Bounced'), ('opened', '👁️ Opened'), ('clicked', '🔗 Clicked')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID from SendGrid/Mailgun/etc for tracking', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Error details if send failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When email was queued')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When email was actually sent', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last status update')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='accounts.company')),
                ('sent_by_agent', models.ForeignKey(help_text='Agent who initiated the email send', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='accounts.session')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='accounts.emailtemplate')),
            ],
            options={
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['company', 'template_type', 'is_active'], name='accounts_em_company_7b71df_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['session', 'status'], name='accounts_em_session_3ba1ba_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_email'], name='accounts_em_to_emai_96907b_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['company'], name='accounts_em_company_890bf2_idx'),
        ),
    ]
