# Generated by Django 5.2.7 on 2025-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_session_user_email_session_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_provider', models.CharField(choices=[('sendgrid', 'Twilio SendGrid'), ('mailgun', 'Mailgun'), ('amazon_ses', 'Amazon SES'), ('mailjet', 'Mailjet'), ('postmark', 'Postmark'), ('smtp', 'Custom SMTP'), ('console', 'Console (Local Dev)')], default='console', help_text='Select the active email service provider', max_length=20)),
                ('default_from_email', models.EmailField(default='noreply@example.com', help_text="Default 'From' address (e.g., noreply@yourdomain.com)", max_length=254)),
                ('from_name', models.CharField(default='Control Room', help_text="Friendly name (e.g., 'Security Team')", max_length=255)),
                ('sendgrid_api_key', models.CharField(blank=True, help_text='SG.xxxx...', max_length=255)),
                ('mailgun_api_key', models.CharField(blank=True, max_length=255)),
                ('mailgun_sender_domain', models.CharField(blank=True, help_text='mg.yourdomain.com', max_length=255)),
                ('aws_access_key_id', models.CharField(blank=True, max_length=255)),
                ('aws_secret_access_key', models.CharField(blank=True, max_length=255)),
                ('aws_region', models.CharField(blank=True, default='us-east-1', max_length=50)),
                ('mailjet_api_key', models.CharField(blank=True, max_length=255)),
                ('mailjet_secret_key', models.CharField(blank=True, max_length=255)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS (recommended for port 587)')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL (usually port 465)')),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_redirect_url', models.URLField(default='https://google.com', help_text="Where to redirect users after 'Begin KYC' (e.g., Ballerine URL)")),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If active, new sessions cannot be started')),
                ('support_phone', models.CharField(blank=True, help_text='Global support phone number displayed to users', max_length=20)),
                ('support_email', models.EmailField(blank=True, help_text='Global support email address', max_length=254)),
                ('max_daily_verifications', models.IntegerField(default=1000, help_text='Safety cap for daily verifications to prevent abuse')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
