# Generated by Django 5.2.7 on 2025-12-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailsettings_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='brevo_api_key',
            field=models.CharField(blank=True, help_text='v3 API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='mailgun_webhook_signing_key',
            field=models.CharField(blank=True, help_text='For signed webhooks', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='postmark_account_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='postmark_server_token',
            field=models.CharField(blank=True, help_text='X-Postmark-Server-Token', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='sendgrid_webhook_verification_key',
            field=models.CharField(blank=True, help_text='For signed webhooks', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='sparkpost_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Shared secret for webhook basic auth (Brevo, SparkPost, etc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_provider',
            field=models.CharField(choices=[('console', 'Console (Local Dev)'), ('smtp', 'Custom SMTP'), ('sendgrid', 'Twilio SendGrid'), ('mailgun', 'Mailgun'), ('amazon_ses', 'Amazon SES'), ('mailjet', 'Mailjet'), ('postmark', 'Postmark'), ('brevo', 'Brevo (Sendinblue)'), ('sparkpost', 'SparkPost')], default='console', help_text='Select the active email service provider', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='mailgun_sender_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='sendgrid_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
