"""
Django settings for control_room project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*@1nkp29@*)t7jnk5&sixk=^o0iip0vp&k26%&%ua0wr#l!&il'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",") if os.environ.get("ALLOWED_HOSTS") else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps Required
    'channels',
    'accounts',
    
    # API
    'rest_framework',
    'rest_framework_simplejwt',

    # CORS
    'corsheaders',
]


MIDDLEWARE = [
    #CORS
    'corsheaders.middleware.CorsMiddleware',


    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware', #wWhitenoise static files serve since daphenen doesnt serve static files so no css :(

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    
]

ROOT_URLCONF = 'control_room.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Django uses WSGI for normal HTTP requests, and ASGI for WebSockets.
WSGI_APPLICATION = 'control_room.wsgi.application'

# Use ASGI instead of WSGI for Channels
ASGI_APPLICATION = 'control_room.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Database configuration from Environment Variables
DB_ENGINE = os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')
DB_NAME = os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3')
DB_USER = os.environ.get('DB_USER', '')
DB_PASSWORD = os.environ.get('DB_PASSWORD', '')
DB_HOST = os.environ.get('DB_HOST', '')
DB_PORT = os.environ.get('DB_PORT', '')

if DB_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DB_NAME,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Let Django know where to find additional static files inside apps
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# Whitenoise compressed storage for efficient serving
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Redis Channel Layer Configuration
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', 6379)
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', None)
REDIS_SSL = os.environ.get('REDIS_SSL', 'False').lower() == 'true'

print(f"DEBUG SETTINGS: REDIS_HOST={REDIS_HOST!r}")
print(f"DEBUG SETTINGS: REDIS_SSL={REDIS_SSL!r}")

def get_redis_channel_layer_hosts():
    print("DEBUG SETTINGS: Inside get_redis_channel_layer_hosts")
    # If the user provided a full URL in REDIS_HOST, use it directly
    if '://' in REDIS_HOST:
        print("DEBUG SETTINGS: Using REDIS_HOST directly")
        return [REDIS_HOST]

    if REDIS_SSL:
        print("DEBUG SETTINGS: Configuring SSL URL")
        # Construct rediss:// URL for robust SSL handling in channels_redis
        # Scheme
        url = f"rediss://{REDIS_HOST}:{REDIS_PORT}"
        
        # Auth (if password exists)
        if REDIS_PASSWORD:
            url = f"rediss://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
            
        # Query Params for SSL options
        params = []
        cert_reqs = os.environ.get("REDIS_SSL_CERT_REQS", "required").lower()
        
        # redis-py parse_url handles "none", "optional", "required"
        if cert_reqs == "none":
            params.append("ssl_cert_reqs=none")
        elif cert_reqs == "optional":
            params.append("ssl_cert_reqs=optional")
        elif cert_reqs == "required":
             params.append("ssl_cert_reqs=required")
             
        if params:
            url += "?" + "&".join(params)
            
        return [url]

    # Non-SSL: Use explicit dictionary configuration
    config = {
        "host": REDIS_HOST,
        "port": int(REDIS_PORT),
    }

    if REDIS_PASSWORD:
        config["password"] = REDIS_PASSWORD

    return [config]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": get_redis_channel_layer_hosts(),
            "on_disconnect": "disconnect",
             # Prevent connection leaks
            "capacity": 1500,
            "expiry": 10,
        },
    },
}



# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}




# Authentication settings
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# Session settings (for agent-user pairing)
SESSION_COOKIE_AGE = 43200  # 12 hours (Standard business day)
SESSION_SAVE_EVERY_REQUEST = True




CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "http://localhost:5173").split(",")

# CORS frontend origin:
CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:5173,http://localhost:3000,http://127.0.0.1:3000,http://localhost:4000").split(",")

# Trust headers from Traefik
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# KYC Configuration
KYC_REDIRECT_URL = os.environ.get("KYC_REDIRECT_URL", "https://google.com")
